TEST TO SHOW THAT WE ONLY USE serialize_scalar() TO SERIALIZE INDEXES.
This breaks (correctly) with:
$ make
make  all-am
make[1]: Entering directory '/home/muxator/code/itcoin/secp256k1-frost'
  CC       src/libsecp256k1_la-secp256k1.lo
In file included from src/secp256k1.c:817:
src/modules/frost/main_impl.h: In function 'generate_dkg_challenge':
src/modules/frost/main_impl.h:592:22: error: incompatible type for argument 1 of 'serialize_scalar'
  592 |     serialize_scalar(index, &(challenge_input[SERIALIZED_PUBKEY_X_ONLY_SIZE + SERIALIZED_PUBKEY_X_ONLY_SIZE]));
      |                      ^~~~~
      |                      |
      |                      uint32_t {aka unsigned int}
src/modules/frost/main_impl.h:115:53: note: expected 'secp256k1_scalar' but argument is of type 'uint32_t' {aka 'unsigned int'}
  115 | static void serialize_scalar(const secp256k1_scalar value, unsigned char *ret) {
      |                              ~~~~~~~~~~~~~~~~~~~~~~~^~~~~
src/modules/frost/main_impl.h: In function 'encode_group_commitments':
src/modules/frost/main_impl.h:979:30: error: incompatible type for argument 1 of 'serialize_scalar'
  979 |         serialize_scalar(item.index, &(buffer[identifier_idx]));
      |                          ~~~~^~~~~~
      |                              |
      |                              uint32_t {aka unsigned int}
src/modules/frost/main_impl.h:115:53: note: expected 'secp256k1_scalar' but argument is of type 'uint32_t' {aka 'unsigned int'}
  115 | static void serialize_scalar(const secp256k1_scalar value, unsigned char *ret) {
      |                              ~~~~~~~~~~~~~~~~~~~~~~~^~~~~
src/modules/frost/main_impl.h: In function 'compute_binding_factor':
src/modules/frost/main_impl.h:1016:22: error: incompatible type for argument 1 of 'serialize_scalar'
 1016 |     serialize_scalar(index, &(rho_input[SHA256_SIZE + SHA256_SIZE]));
      |                      ^~~~~
      |                      |
      |                      uint32_t {aka unsigned int}
src/modules/frost/main_impl.h:115:53: note: expected 'secp256k1_scalar' but argument is of type 'uint32_t' {aka 'unsigned int'}
  115 | static void serialize_scalar(const secp256k1_scalar value, unsigned char *ret) {
      |                              ~~~~~~~~~~~~~~~~~~~~~~~^~~~~
make[1]: *** [Makefile:1207: src/libsecp256k1_la-secp256k1.lo] Error 1
make[1]: Leaving directory '/home/muxator/code/itcoin/secp256k1-frost'
make: *** [Makefile:939: all] Error 2