coverage: work around two bugs in gcovr
Either gcovr 8.3 or gcc 14.2 cause an, which is also reproducible locally, when
running the job "Functional tests with code coverage, no -Werror" (see later).

This PR is an attempt at mitigating it: we transform the gcovr error in a
warning following an advice by gcovr itself.

Other (and better) strategies, such as adding `-fprofile-update=atomic` as
suggested in https://gcc.gnu.org/bugzilla/show_bug.cgi?id=68080#c4 and
documented in https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html#index-fprofile-update
did not help solve the problem.

In order to be as strict as possible, we then require that a fixed, hard coded
set of warnings must be generated, because we want to be aware of every possible
variation in the coverage analysis.

In the process, we have to counter-hack gcovr, that diabolically behaves
differently when it detects that it is running in a GitHub worker
(https://github.com/gcovr/gcovr/blob/0a426ca4baae56607f7cff2188569b3dbfc9af13/src/gcovr/logging.py#L79-L83).

The following is the error that gcovr generates unless we use
`--gcov-ignore-parse-errors=suspicious_hits.warn`:

```
[...] a bug in gcov tool, see
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=68080. Use option
--gcov-ignore-parse-errors with a value of suspicious_hits.warn, or
suspicious_hits.warn_once_per_file or change the threshold for the detection
with option --gcov-suspicious-hits-threshold.

(ERROR) Error occurred while reading reports:
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/gcovr/__main__.py", line 384, in main
    covdata = gcovr_formats.read_reports(options)
  File "/usr/lib/python3.13/site-packages/gcovr/formats/__init__.py", line 99, in read_reports
    covdata = GcovHandler(options).read_report()
  File "/usr/lib/python3.13/site-packages/gcovr/formats/gcov/__init__.py", line 233, in read_report
    return read_report(self.options)
  File "/usr/lib/python3.13/site-packages/gcovr/formats/gcov/read.py", line 96, in read_report
    contexts = pool.wait()
  File "/usr/lib/python3.13/site-packages/gcovr/formats/gcov/workers.py", line 181, in wait
    raise RuntimeError(
        "Worker thread raised exception, workers canceled."
    ) from None
RuntimeError: Worker thread raised exception, workers canceled.
```